[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
shadowlend_program = "J6hwZmTBYjDQdVdbeX7vuhpwpqgrhHUqQaUk8qYsZvXK"

[programs.localnet]
shadowlend_program = "J6hwZmTBYjDQdVdbeX7vuhpwpqgrhHUqQaUk8qYsZvXK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "F3G6Q9tRicyznCqcZLydJ6RxkwDSBeHWM458J7V6aeyk"
program = "/home/glitchy_moon/glitchy_moon/github_repo/ShadowLend/shadowlend_program/artifacts/arcium_program_0.5.4.so"

[[test.genesis]]
address = "L2TExMFKdjpN9kozasaurPirfHy9P8sbXoAN1qA3S95"
program = "artifacts/lighthouse.so"

[test.validator]
bind_address = "127.0.0.1"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EQr6UCd7eyRjpuRsNK6a8WxkgrpSGctKMFuz92FRRh63"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "BSC6rWJ9ucqZ6rcM3knfpgdRwCyJ7Q9KsddjeSL4EdHq"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "9AVaR6JcQaX6CJwg5fNivx2qEAQ2nKAn86DRi7vL5kK2"
filename = "artifacts/wallet_acc_9AVa_5kK2.json"

[[test.validator.account]]
address = "5hAvtE7yzxjtSqnLnAuUAV4W3so472SAmFtWzDPVe5zi"
filename = "artifacts/arx_ata_9AVa_5kK2.json"

[[test.validator.account]]
address = "5Bg5Nudnj1GufVoKu3Sq6o4jr3WkdbvproSgYvtWXbnT"
filename = "artifacts/wallet_acc_5Bg5_XbnT.json"

[[test.validator.account]]
address = "5FMyCSA4mFeus49BE2qzsXiwxb1ZoUGkoqSM9xz6be9i"
filename = "artifacts/wallet_acc_callback_5FMy_be9i.json"

[[test.validator.account]]
address = "GyJcqYRYH1ZMVA4uuz6e9HH7qCzCB79D4PkN3W6uMmje"
filename = "artifacts/arx_ata_5Bg5_XbnT.json"

[[test.validator.account]]
address = "7H2pfwgYDweV6cVUiUEfabiN7YYRpgekRQwoEvkREwED"
filename = "artifacts/operator_acc_5Bg5_XbnT.json"

[[test.validator.account]]
address = "9CaJVqHPWPGRDY1x7Eew5a3BuTcCYm8JQXmk8coE1Zkf"
filename = "artifacts/arx_node_5Bg5_XbnT.json"

[[test.validator.account]]
address = "93TBiGar5NX8WrTYWNpkLGnnmu1uJxifvPzzmzYXWuhu"
filename = "artifacts/wallet_acc_93TB_Wuhu.json"

[[test.validator.account]]
address = "tsyNGB1ebYTVeNNbjB1JiR4Z4nU9bAW7byssFFcVFGg"
filename = "artifacts/wallet_acc_callback_tsyN_VFGg.json"

[[test.validator.account]]
address = "ypctFL2A62fnnAZSmLh22nRZEVrMd2xWazX9pT8zHDa"
filename = "artifacts/arx_ata_93TB_Wuhu.json"

[[test.validator.account]]
address = "FQFDpoum1NxW9uJUES1PpAGntSj9gNBmbFk7mDR5VCVj"
filename = "artifacts/operator_acc_93TB_Wuhu.json"

[[test.validator.account]]
address = "HwMdVdMkep2njXpEVZmWrbYPtsGdpJJvZzSb673YMZBy"
filename = "artifacts/arx_node_93TB_Wuhu.json"

[[test.validator.account]]
address = "3kMQur1kfAYp5JeoXRq11CUnP5x8DT5dw12rHnfoJNPg"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "mdDyYNfzoFdKfpyi7ZVrzWm2dveWsSMv7noodWgD8P5"
filename = "artifacts/compute_confidential_repay_raw_circuit_0.json"

[[test.validator.account]]
address = "51hugRXx1EwgWdxWHyLywy61uney816imLbsgLyVjG4E"
filename = "artifacts/compute_confidential_deposit_raw_circuit_0.json"

[[test.validator.account]]
address = "5ZuB9Q5FZZDoJe2jsjiajpxmgdRJHvpJpFx58RP3zkex"
filename = "artifacts/compute_confidential_liquidate_raw_circuit_0.json"

[[test.validator.account]]
address = "3yAHqCCRQN9K55zkx5LfsHrqpzFXzXvypFFfNJ5UQVYm"
filename = "artifacts/compute_confidential_liquidate_raw_circuit_1.json"

[[test.validator.account]]
address = "7AuW8WGmXUJiYrUQLbEVweDUwoGfQdt7mHJPhd9rWEpg"
filename = "artifacts/compute_confidential_borrow_raw_circuit_0.json"

[[test.validator.account]]
address = "5wAhTTonBD5jD2UfG9vbF5z85yQcSmTEHQVKCJFTtT3m"
filename = "artifacts/compute_confidential_withdraw_raw_circuit_0.json"

[[test.validator.account]]
address = "621GZgmnQUMFFk4pewBvcKS2ctKegjdiwnpdohc385hH"
filename = "artifacts/compute_confidential_interest_raw_circuit_0.json"

[[test.validator.account]]
address = "HwYPePxDU96mMxhQMeHDqyTTT1MvVnr8oXSUirPNdq3i"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "4E1eBF7cH7ZDkEWkupB63B8PugCnGkuV5uzcfpcCoSXC"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "DEY2p2t3dP5QbCtGAfBhGt7HMfoBc3o86EyxD4iqE1xR"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "RJ56J5zMy5yXFYcWHjcQfdT2f2PQAGMom7UMyHw3kkj"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "8dZouGFqvrkVS6wgzwynwvQNvnHqPdyi8Eq1Zm6z4KSi"
filename = "artifacts/executing_pool_acc.json"
