// Deposit instruction module
//
// Handles depositing collateral into the lending pool.
// Uses Arcium MXE to keep individual deposit amounts private.

mod accounts;
mod callback;
mod handler;

pub use accounts::*;
pub use callback::*;
pub use handler::*;

// Re-export the output type for lib.rs
// Note: ComputeDepositOutput is auto-generated by Arcium from the circuit
